config/routes.rb
Rails.application.routes.draw do
root to: 'public/homes#top'
namespace :admin do
    root to: "homes#top"
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    
    resources :orders, only: [:show, :index, :update]
    resources :order_details, only: [:update]
  end
namespace :public do
    root to: 'homes#top'
    get "/homes/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    
    get "/customers/my_page" => "customers#show", as: "customers_my_page"
    get "/customers/quit" => "customers#quit", as: "quit"
    patch "/customers/out" => "customers#out", as: "out"
    
    resources :customers, only: [:edit, :update]
    
    delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all"
    post "cart_items/create"=>"cart_items#create",as: "create"
    resources :cart_items, only: [:index, :update, :destroy,:create]
    
    post "/orders/thanx" => "orders#thanx", as: "thanx"
    post "/orders/create" => "orders#create", as: "orders_create"
    post "/orders/confirm" => "orders#confirm",as: "confirm"
    resources :orders, only: [:new, :create, :index, :show]
    
    
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    delete "/addresses/:id"=> "addresses#destroy",as: "addresses_destroy"
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  } 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!
    
    def index
        @customers = Customer.page(params[:page])
    end
    
    def show
        @customer=Customer.find(params[:id])
    end
    
    def edit
        @customer=Customer.find(params[:id])
    end
    
    def update
        @customer=Customer.find(params[:id])
        if  @customer.update(customer_params)
            redirect_to admin_customer_path
        else
            render:edit
        end
    end   
    
    private
    def customer_params
        params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:email,:is_deleted)
    end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :customer_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  protected
# 退会しているかを判断するメソッド
def customer_state
  ## 【処理内容1】 入力されたemailからアカウントを1件取得
  @customer = Customer.find_by(email: params[:customer][:email])
  ## アカウントを取得できなかった場合、このメソッドを終了する
  return if !@customer
  ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
  if @customer.valid_password?(params[:customer][:password])
    ## 【処理内容3】
  end
end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h3 class="m-5"><%= @customer.last_name%><%= @customer.first_name %>さんの会員情報編集</h3>
<div class="mx-5">
<%= form_with model: @customer, url: admin_customer_path(@customer.id), local: true do |f| %>
    <div class="my-4">
      <span class="mx-5">会員ID</span>
      <%= @customer.id %>
    </div>
      
   <div class="my-4">
      <span class="mx-5">氏名</span>
      <%= f.text_field :last_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="my-4">
      <span class="mx-5">フリガナ</span>
      <%= f.text_field :last_name_kana %>
      <%= f.text_field :first_name_kana %>
    </div>
    <div class="my-4">
      <span class="mx-5">郵便番号</span>
      <%= f.text_field :postal_code %>
    </div>
    <div class="my-4">
      <span class="mx-5">住所</span>
      <%= f.text_field :address, size:50 %>
    </div>
    <div class="my-4">
      <span class="mx-5">電話番号</span>
      <%= f.text_field :telephone_number %>
    </div>
    <div class="my-4">
      <span class="mx-5">メールアドレス</span>
      <%= f.text_field :email %>
    </div>
    <div class="my-4">
      <span class="mx-5">会員ステータス</span>
      <%= f.radio_button :is_deleted,:false %>有効
      <%= f.radio_button :is_deleted,:true %>退会
      
    </div>
    <div class="mx-5">
      <%= f.submit "変更を保存", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
<h4 class="my-3">会員一覧</h4>
 <table class="table table-bordered">
    <thead class="table-secondary">
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
    </thead>
    
     <tbody class="my-3 mx-4">
      <tr>
       <% @customers.each do |customer| %>
        <td>
          <%= customer.id %>
        </td>
    
        <td>
        <%= link_to admin_customer_path(customer.id) do %>
          <%= customer.last_name %><%= customer.first_name %>
        <% end %>
        </td>
    
        <td><%= customer.email %></td>
    
        <td>
       <% if customer.is_deleted == false %>
        <p class="text-success">有効</p>
       <% else %>
        <p class="text-muted">無効</p>
       <% end %>
        </td>
      </tr>
      <% end %>
     </tbody>
    </table>
  </div>

 <div class="mx-auto" style="width: 200px;">
   <%= paginate @customers %>
 </div>  

app/views/admin/customers/show.html.erb
<h3 class="m-5"><%= @customer.last_name%><%= @customer.first_name %>さんの会員詳細</h3>
<div class="mx-5">
  <div class="my-4">
    <span class="mx-5">会員ID</span>
    <%= @customer.id %>
  </div>
  <div class="my-4">
    <span class="mx-5">氏名</span>
    <%= @customer.last_name %><%= @customer.first_name %>
  </div>
  <div class="my-4">
    <span class="mx-5">フリガナ</span>
    <%= @customer.last_name_kana %> <%= @customer.first_name_kana %>
  </div>
  <div class="my-4">
    <span class="mx-5">郵便番号</span>
    <%= @customer.postal_code %>
  </div>
  <div class="my-4">
    <span class="mx-5">住所</span>
    <%= @customer.address %>
  </div>
  <div class="my-4">
    <span class="mx-5">電話番号</span>
    <%= @customer.telephone_number %>
  </div>
  <div class="my-4">
    <span class="mx-5">メールアドレス</span>
    <%= @customer.email %>
  </div>

  <div class="my-4">
    <span class="mx-5">会員ステータス</span>
      <% if @customer.is_deleted == false %>
        <span class="text-success">有効</span>
      <% else %>
        <span class="text-muted">退会</span>
      <% end %>
  </div>

<div class="mx-5 my-5">
    <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: 'btn btn-success' %>
    <%= link_to "注文履歴一覧を見る", admin_orders_path, class: 'btn btn-primary' %>
</div>