config/routes.rb
Rails.application.routes.draw do
root to: 'public/homes#top'
namespace :admin do
    root to: "homes#top"
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    
    resources :orders, only: [:show, :index, :update]
    resources :order_details, only: [:update]
  end
namespace :public do
    root to: 'homes#top'
    get "/homes/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    
    get "/customers/my_page" => "customers#show", as: "customers_my_page"
    get "/customers/quit" => "customers#quit", as: "quit"
    patch "/customers/out" => "customers#out", as: "out"
    
    resources :customers, only: [:edit, :update]
    
    delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all"
    post "cart_items/create"=>"cart_items#create",as: "create"
    resources :cart_items, only: [:index, :update, :destroy,:create]
    
    post "/orders/thanx" => "orders#thanx", as: "thanx"
    post "/orders/create" => "orders#create", as: "orders_create"
    post "/orders/confirm" => "orders#confirm",as: "confirm"
    resources :orders, only: [:new, :create, :index, :show]
    
    
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    delete "/addresses/:id"=> "addresses#destroy",as: "addresses_destroy"
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  } 
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    validates :name, presence: true
    validates :postal_code, presence: true
    validates :address, presence: true
    
    def address_display
    '〒' + postal_code + '' + address + '' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    has_one_attached :image
    
    def subtotal
        item.with_tax_price * amount
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items
    has_many :order_details
    belongs_to :genre
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence:true
    
    has_one_attached :image
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    
  belongs_to :customer
  has_many :order_details
  
  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }

      
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :item
    belongs_to :order

    enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

    def subtotal
         item.with_tax_price * amount
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path(@genre.id)
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre.id)
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
 
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!
  def new
    @item = Item.new
  end
  
  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render:new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_items_path(@item.id)
    else
      render:edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :image, :image_id, :name, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
     before_action :authenticate_admin!
  def index
      @orders = Order.page(params[:page])
      
  end 
  
  def show
    @order = Order.find(params[:id])
   
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.status == "payment_confirmation"
      @order.order_details.each do |order_detail|
        order_detail.making_status = "production_pending"
        order_detail.save
      end
    end
    redirect_to admin_order_path(@order.id)
  end


  private

  def order_params
    params.require(:order).permit(:order_id,:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<% if @genre.errors.any? %>
  <%= @genre.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<h3 class="m-5">ジャンル編集</h3>
<div class="mx-auto" style="width: 700px;">
    <%= form_with model: @genre, url: admin_genre_path, local: true do |f| %>
    <div class="my-4">
        <span class="mx-3"><%= f.label :ジャンル名 %></span>
 　     <%= f.text_field :name %>
　      <span class="mx-3"><%= f.submit "変更を保存" , class: 'btn btn-success' %></span>
    </div>　　
    <% end %>
</div>

app/views/admin/genres/index.html.erb
<% if @genre.errors.any? %>
  <%= @genre.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @genre.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<h3 class="m-5">ジャンル一覧・追加</h3>
 <div class="mx-5" style="width: 700px;">
    <%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
      <div class="my-4">
        <span class="mx-1"><%= f.label :name, "ジャンル名" %></span>
        <%= f.text_field :name %>
        <span class="mx-1"><%= f.submit '新規登録', class: 'btn btn-success' %></span>
      </div>
    <% end %>
</div>
<div class="mx-5" style="width: 500px;">
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>ジャンル</th>
        <th></th>
      </tr>
    </thead>
    <% @genres.each do |genre| %>
    <tbody>
      <tr>
        <td><%= genre.name %></td>
        <td><%= link_to '編集する', edit_admin_genre_path(genre), class: 'btn btn-success' %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

app/views/admin/items/edit.html.erb
<% if @item.errors.any? %>
  <%= @item.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<h3 class="m-5">商品編集</h3>
<div class="mx-auto" style="width: 600px;">
  <%= form_with model:[:admin,@item], local:true do |f| %>
    <div class="my-4">
      <span class="mx-5"><%= f.label :image, "商品画像" %></span>
      <%= f.file_field :image, accept:"image/*" %>
    </div>
    <div class="my-4">
      <span class="mx-5"><%= f.label :name, "商品名　" %></span>
      <%= f.text_field :name, size:47 %>
    </div>
    <div class="my-4">
      <span class="mx-5"><%= f.label :introduction, "商品説明" %></span>
      <%= f.text_area :introduction, size:'50*50' %>
    </div>
    <div class="my-4">
      <span class="mx-5"><%= f.label :genre_id, "ジャンル" %></span>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name) %>
    </div>
    <div class="my-4">
      <span class="mx-5"><%= f.label :price, "税抜価格" %></span>
      <%= f.text_field :price, size:47 %>円
    </div>
    <div class="my-4">
      <span class="mx-5"><%= f.label :price, "税抜価格" %></span>
      <span class="mx-5"><%= f.radio_button :is_active, :true %>販売中</span>
      <span class="mx-5"><%= f.radio_button :is_active, :false %>販売停止中</span>
    </div>
    <div class="mx-5">
      <%= f.submit "変更を保存", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>
        
    

app/views/admin/items/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-8 ml-3">
      <h3 class="m-5">商品一覧</h3>
    </div>
    <div class="col-3 ml-3 m-3">
      <%= link_to  new_admin_item_path do %>
        <i class="fas fa-plus-circle fa-3x">+</i>
      <% end %>  
    </div>
  </div>
</div>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-12 ml-3">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @items.each do |item| %>
          <tbody>
            <tr>
              <td><%= item.id %></td>
              <td>
                <%= link_to admin_item_path(item.id) do %>
                  <%= item.name %>
                <% end %>
              </td>
              <td><%= item.price %></td>
              <td><%= item.genre.name %></td>
              <td>
                <% if item.is_active == true %>
                  販売中
                <% else %>
                  販売停止中
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
      <div class="mx-auto" style="width: 200px;">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
 <% if @item.errors.any? %>
  <%= @item.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 
<h3 class="m-5">商品新規登録</h3>
<div class="mx-auto" style="width: 700px;">
  <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
   
    <div class="my-4">
      <span class="mx-5"><%= f.label :image, "商品画像" %></span>
      <%= f.file_field :image, accept:"image/*" %>
    </div>
    <%= f.hidden_field :image_id %>
    <div class="my-4">
      <span class="mx-5"><%= f.label :name, "商品名　" %></span>
      <%= f.text_field :name, size:47 %>
    </div>
    <div class="my-4">
      <span class="mx-5"><%= f.label :introduction, "商品説明" %></span>
      <%= f.text_area :introduction, placeholder: "ここに説明文を記述します" %>
    </div>
    <div class="my-4">
      <span class="mx-5"><%= f.label :genre_id, "ジャンル" %></span>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank: "--選択してください--"}) %>
    </div>
    <div class="my-4">
      <span class="mx-5"><%= f.label :price, "税抜価格" %></span>
      <%= f.text_field :price, size:47 %>円
    </div>

    <div class="my-4">
     <span class="mx-5"><%= f.label :販売ステータス %></span>
        <span class="mx-5"><%= f.radio_button :is_active, :true %>販売中</span>
        
        <span class="mx-5"><%= f.radio_button :is_active, :false %>販売中止</span>
    </div>
    
     <div class="mx-5">
      <%= f.submit "新規登録", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<h2 class="btn btn-secondary btn-lg mb-5">商品詳細</h2>

<div class="container">
  <div class="row">

    <div class="col-lg-4">
      <%= image_tag @item.image,size: "250x250" %>
    </div>
    
    <div class="col-lg-8">
     <table class="table table-borderless">
      <tbody>
        <tr>
          <th style="width: 25%">商品名</th>
          <th style="width: 75%"><%= @item.name %></th>
        </tr>
        <tr>
          <th>商品説明</th>
          <th><%= @item.introduction %></th>
        </tr>
        <tr>
          <th>ジャンル</th>
          <th><%= @item.genre.name %></th>
        </tr>
        <tr>
          <th>税込価格<br>（税抜価格）</th>
          <th><%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</th>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <th>
          <% if @item.is_active == true %>
            <p class="text-success">販売中</p>
          <% else %>
            <p class="text-muted">販売停止中</p>
          <% end %>
          </th>
        </tr>
      </tbody>
     </table>
    <%= link_to '編集する', edit_admin_item_path(@item.id), class: 'btn btn-success' %>
    </div>
  </div>
</div>  

app/views/admin/orders/index.html.erb
<h3 class="m-5">注文履歴一覧</h3>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-12 ml-3">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
      <% @orders.each do |order| %>
        <tbody>
          <tr>
            <td>
              <%= link_to admin_order_path(order.id) do %>
                <%= order.created_at.strftime('%Y/%m/%d') %>
              <% end %>
            </td>
            <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
            <td>
              <%= order.order_details.all.sum(:amount) %>
            </td>
            <td><%= order.status_i18n %></td>
          </tr>
        </tbody>
      <% end %>
      </table>
      <div class="mx-auto" style="width: 200px;">
        <%= paginate @orders %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<h3 class="m-5">注文履歴詳細</h3>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-8 ml-3">
      <table class="table table-bordered m-3">
        <tbody>
          <tr>
            <td>
              <b>購入者</b>
            </td>
            <td><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
          </tr>
          <tr>
            <td>
              <b>注文日</b>
            </td>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <td>
              <b>配送先</b>
            </td>
            <td>
              <div>〒<%= @order.post_code %></div>
              <div><%= @order.address %></div>
              <div><%= @order.customer.last_name %><%= @order.customer.first_name %></div>
            </td>
          </tr>
          <tr>
            <td>
              <b>支払方法</b>
            </td>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <td>
              <b>注文ステータス</b>
            </td>
            <td>
            <%= form_with model:@order, url: admin_order_path(@order.id), method: :patch, local:true do |f| %>
              <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
              <%= f.submit "更新", class: "btn btn-success btn-sm" %>
            </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-8 ml-3">
      <table class="table table-bordered m-3">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <% @order.order_details.each do |order_detail| %>
        <tbody>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.item.price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.subtotal.to_s(:delimited) %></td>
            <td>
             <%= form_with model:[:admin,order_detail], url: admin_order_detail_path(order_detail.id), method: :patch, local:true do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
              <%= f.submit "更新", class: "btn btn-success btn-sm" %>
             <% end %>
            </td>
            
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
    <div class="col-4 ml-3">
      <table class="table table-bordered m-3">
        <tbody>
          <tr>
            <td>
              <b>商品合計</b>
            </td>
            <td><%= (@order.total_payment - @order.postage).to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <td>
              <b>送料</b>
            </td>
            <td><%= @order.postage.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <td>
              <b>請求金額合計</b>
            </td>
            <td><%= @order.total_payment.to_s(:delimited) %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>