config/routes.rb
Rails.application.routes.draw do
root to: 'public/homes#top'
namespace :admin do
    root to: "homes#top"
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    
    resources :orders, only: [:show, :index, :update]
    resources :order_details, only: [:update]
  end
namespace :public do
    root to: 'homes#top'
    get "/homes/about" => "homes#about", as: "about"
    resources :items, only: [:index, :show]
    
    get "/customers/my_page" => "customers#show", as: "customers_my_page"
    get "/customers/quit" => "customers#quit", as: "quit"
    patch "/customers/out" => "customers#out", as: "out"
    
    resources :customers, only: [:edit, :update]
    
    delete "/cart_items/destroy_all" => "cart_items#destroy_all", as: "destroy_all"
    post "cart_items/create"=>"cart_items#create",as: "create"
    resources :cart_items, only: [:index, :update, :destroy,:create]
    
    post "/orders/thanx" => "orders#thanx", as: "thanx"
    post "/orders/create" => "orders#create", as: "orders_create"
    post "/orders/confirm" => "orders#confirm",as: "confirm"
    resources :orders, only: [:new, :create, :index, :show]
    
    
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    delete "/addresses/:id"=> "addresses#destroy",as: "addresses_destroy"
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  } 
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    validates :name, presence: true
    validates :postal_code, presence: true
    validates :address, presence: true
    
    def address_display
    '〒' + postal_code + '' + address + '' + name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    has_one_attached :image
    
    def subtotal
        item.with_tax_price * amount
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :cart_items
    has_many :order_details
    belongs_to :genre
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence:true
    
    has_one_attached :image
    
    def with_tax_price
        (price * 1.1).floor
    end
end

app/models/order.rb
class Order < ApplicationRecord
    
  belongs_to :customer
  has_many :order_details
  
  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }

      
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :item
    belongs_to :order

    enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

    def subtotal
         item.with_tax_price * amount
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path(@genre.id)
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre.id)
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
 
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!
  def new
    @item = Item.new
  end
  
  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render:new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_items_path(@item.id)
    else
      render:edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :image, :image_id, :name, :introduction, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <h2 class="rounded border border-secondary">LOGO</h2>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              
            <% if admin_signed_in? %>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to '商品一覧', admin_items_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to '注文履歴一覧', admin_orders_path(:id), class: 'nav-link text-dark' %></li>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %></li>
            <% elsif customer_signed_in? %>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to 'マイページ', public_customers_my_page_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to '商品一覧', public_items_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to 'カート', public_cart_items_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %></li>
            <% else %>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to 'About', public_about_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to '商品一覧', public_items_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to '新規登録',new_customer_registration_path, class: 'nav-link text-dark' %></li>
              <li class="nav-item m-1 rounded border border-muted"><%= link_to 'ログイン', new_customer_session_path, class: 'nav-link text-dark' %></li>
            <% end %>
            </ul>
          </div>
        </div>
    </header>
    <main class="container mt-5">
    <%= yield %>
  </main>

　<footer class="mt-auto py-3 bg-dark">
　  <div class="text-center text-white">Sweets make you happy</div>
　</footer>
  </body>
</html>